fix: Do not pass numeric arguments to res.send
GoogleCloudPlatform/functions-framework-nodejs pull request #242
Opened 2020-12-24 17:09 UTC by sk-

Fixes #239.

res.send when receiving a sole numeric argument will set thee statuc code to that number.

This breaks HTTP communication as some numbers are not valid HTTP response codes.

For example, in the original issue the code is being set to 2. Which probably comes from the UNKNOWN error response of an RPC call.

This makes that the function is reported as having a `connection error`.

2021-01-29 17:47 UTC, grant requested changes
Sorry for the delay in reviewing. To fix the error, I suggest the logic be a bit simpler – we convert the crash response to always be a string.

2021-01-29 17:47 UTC, grant commented on src/logger.ts
> +    res.send(sanitizedMessage);
```ts
// Send string response
res.send((err.message || err) +'');
```

2021-01-29 20:26 UTC, sk- commented on src/logger.ts
> +    res.send(sanitizedMessage);
Done.

2021-01-29 20:36 UTC, grant approved these changes

2021-01-29 20:46 UTC, merged

2021-01-29 20:48 UTC, grant commented
Will be published in next release of the FF. If there's urgency to publish this, ping here.

2022-07-02 11:18 UTC, Jkudjo commented
found this useful in my application. Gracias