ci: conformance action 2
GoogleCloudPlatform/functions-framework-nodejs pull request #262
Opened 2021-03-23 20:25 UTC by grant

WIP conformance PR

2021-04-06 23:13 UTC, grant commented
Should be ready to review @mtraver. Pardon the large PR.
We can move parts of the changes to a separate PR is needed.

2021-04-13 21:33 UTC, matthewrobertson commented on src/cloudevents.ts
> +export function getStructuredCloudEventContext(
I am a bit confused about how this function is different from `convertRequestToStructuredCE`

2021-04-13 21:33 UTC, matthewrobertson commented on src/invoker.ts
> +        context = req.body.context;
Looks like these variables are already initialized to exactly these values on line 186/187. Can we just remove the else block here or remove the initial values above?

2021-04-13 21:33 UTC, matthewrobertson commented on src/invoker.ts
> +      if (!context) {
nit: flatten to `} else if (!context) {`

2021-04-19 21:34 UTC, matthewrobertson requested changes
Formally requesting changes because I am sure if you saw my review.

2021-04-19 22:20 UTC, grant commented
Thanks. I'll have to apply the comments and likely break this PR into some smaller PRs.

2021-04-21 17:51 UTC, grant commented
I've pulled out a few changes into separate PRs. I think it will make things cleaner and safer:

- https://github.com/GoogleCloudPlatform/functions-framework-nodejs/pull/274
- https://github.com/GoogleCloudPlatform/functions-framework-nodejs/pull/275
- https://github.com/GoogleCloudPlatform/functions-framework-nodejs/pull/276

2021-05-06 19:37 UTC, grant commented
Going to close this PR. Other PRs will be able to complete the conversions. Feel free to ping me if there are questions.

2021-05-06 19:37 UTC, closed without merging